docs_dir: Source

site_name: Reality SDK [0.3]
site_dir: Output
site_url: https://reality.beyondsandbox.com/
site_author: AtlasXR

nav:
  - Home: 'index.md'
  - Getting Started: 'Documentation/GettingStarted.md'
  - Home: 'Documentation/Roadmap.md'
  - Documentation:
    - Interactable:
      - Overview: 'Documentation/Interactable/Overview.md'
      - Create Interactable: 'Documentation/Interactable/CreateInteractable.md'
      - Sharp Area Component: 'Documentation/Interactable/SharpArea.md'
      - Create Firearm: 'Documentation/Interactable/CreateFirearm.md'
    - Gamemode:
      - Overview: 'Documentation/Gamemode/Overview.md'
      - Create Gamemode: 'Documentation/Gamemode/CreateGamemode.md'
    - Feature:
      - Overview: 'Documentation/Feature/Overview.md'
      - Loadout: 'Documentation/Feature/Loadout.md'
      - Class: 'Documentation/Feature/Class.md'
    - Level:
      - Overview: 'Documentation/Level/Overview.md'
      - Create Level: 'Documentation/Level/CreateLevel.md'



  #  - 'Prerequisites': 'Documentation/Prerequisites.md'
    # - 'Create Mod': 'Documentation/CreateMod.md'
  #  - 'Test Mod': 'Documentation/TestMod.md'
  #  - 'Create Level': 'Documentation/CreateMap.md'
  # - API: 'API.md'
  # - Roadmap: 'Roadmap.md'
  # - Download: 'Download.md'

theme:
  include_sidebar: true
  name: material
  logo: Data/Logo.png
  favicon: Data/Logo.png
  font:
    text: Inter
    code: Roboto Mono

  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    annotation: material/information-outline

  palette:
      scheme: black
      primary: black
      accent: black

  features:
    - content.code.copy
    - navigation.previous_next
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.footer

    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

copyright: Copyright &copy; 2025 AtlasXR

extra_css:
  - CSS/style.css

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - toc:
      permalink: true
      toc_depth: '2-4'
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - mkdocs-video
  - search
  - glightbox